### ISSUE TITLE
Improve color scheme

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cargo-tally#10]
I did not find a library for good graph color schemes so there is a quick attempt [here](https://github.com/dtolnay/cargo-tally/blob/0.2.0/src/graph.rs#L20-L26). There is a lot of room for improvement so we need to switch to an approach that is proven to work well for graphs.

**Comment by dtolnay** [comment]
I posted a request for implementation to make this easier to do: https://github.com/dtolnay/request-for-implementation/issues/12.

**Comment by pyfisch** [comment]
There is now https://crates.io/crates/colourado

**Comment by dtolnay** [comment]
This got fixed by just using [D3](https://d3js.org)'s color choices.

https://github.com/dtolnay/cargo-tally/blob/c65c7e3f7e3e5f2aa861ff36d77886daef81a9c7/src/index.html#L37
