### ISSUE TITLE
Graph: fraction of crates.io that depends on lazy_static

### ISSUE THREAD

**Issue by oli-obk** [dtolnay/cargo-tally#11]
![test](https://user-images.githubusercontent.com/332036/33379976-e55e9594-d519-11e7-8c73-304994bc5fa2.png)

cc @kimundi

**Comment by Kimundi** [comment]
Heh, is that 30% now? Crazy!

**Comment by dtolnay** [comment]
:chart_with_upwards_trend:&ensp;38% now

<br>

![Screenshot from 2021-12-14 19-37-09](https://user-images.githubusercontent.com/1940490/146118690-7616ce72-20b4-47dd-8f5d-94f8a2f26e13.png)
