### ISSUE TITLE
WARNING: Plotting with an 'unknown' terminal

### ISSUE THREAD

**Issue by durka** [dtolnay/cargo-tally#16]
Any invocation of `cargo tally --graph ...` produces:

```
WARNING: Plotting with an 'unknown' terminal.
No output will be generated. Please select a terminal with 'set terminal'.
```

And indeed no output is generated.

macOS 10.13, iTerm2 3.0

**Comment by dtolnay** [comment]
Thanks! Sorry I don't have a Mac to debug this with you but [does this help](https://stackoverflow.com/a/46268039/6086311)?

```
brew reinstall gnuplot --with-qt
```

Let me know what ends up working and we can add steps to the readme.

**Comment by durka** [comment]
Yep, works now!

**Comment by dtolnay** [comment]
Okay nice. I added `brew install gnuplot --with-qt` in the readme.
